// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQstLbNbDCRiwiW4__BIr-zvL4IQ1dE0o',
    appId: '1:78034362788:web:987f14c2592ffb41742131',
    messagingSenderId: '78034362788',
    projectId: 'captains-6f267',
    authDomain: 'captains-6f267.firebaseapp.com',
    storageBucket: 'captains-6f267.appspot.com',
    measurementId: 'G-1TXTZ95G6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYGLe9EEH4EqlDCoZwAGlVR_cDAWMHAZ0',
    appId: '1:78034362788:android:ac045c502a95a497742131',
    messagingSenderId: '78034362788',
    projectId: 'captains-6f267',
    storageBucket: 'captains-6f267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAG8wy1y0qvtpEu1YhrM48dmJziNZZsM',
    appId: '1:78034362788:ios:7f4255be8877d805742131',
    messagingSenderId: '78034362788',
    projectId: 'captains-6f267',
    storageBucket: 'captains-6f267.appspot.com',
    iosBundleId: 'com.eshtreeli.captains',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIAG8wy1y0qvtpEu1YhrM48dmJziNZZsM',
    appId: '1:78034362788:ios:8cc46d4eacf10f70742131',
    messagingSenderId: '78034362788',
    projectId: 'captains-6f267',
    storageBucket: 'captains-6f267.appspot.com',
    iosBundleId: 'com.eshtreeli.eshtreeliCaptainsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQstLbNbDCRiwiW4__BIr-zvL4IQ1dE0o',
    appId: '1:78034362788:web:b5fc131c115da4e7742131',
    messagingSenderId: '78034362788',
    projectId: 'captains-6f267',
    authDomain: 'captains-6f267.firebaseapp.com',
    storageBucket: 'captains-6f267.appspot.com',
    measurementId: 'G-X6ESCFBVV9',
  );

}